### ISSUE TITLE
Cannot whitelist methods for pickling.

### ISSUE THREAD

**Issue by andrewplummer** [google/gae-secure-scaffold-python#30]
I'm trying to use the ndb [deferred library](https://cloud.google.com/appengine/articles/deferred) to set up a background task, but this doesn't seem to be supported as I get the error to the effect of `Pickling is forbidden`.

I've tried various methods, but cannot add the methods to the pickle whitelist to get the setup described in the docs.

What would be even better is to allow pickling of any instance method to make this work without having to do something dirty like create custom deferred tasks in `base`, but that seems to be tangential to this issue, as the error doesn't appear to have to do with whitelisting.

**Comment by pames** [comment]
Unfortunately I think this is somewhat "working as intended."

Pickling is quite complex to get right from a security perspective (http://www.cs.jhu.edu/~s/musings/pickle.html) - that's why we patch it in this way.  You could try something like this to figure out what is necessary/missing from your policy:
https://docs.python.org/3/library/pickletools.html

but in the end, the net effect of whitelisting all that could remove all the security benefits, so it may be simpler just to disable the pickle patching in your local fork.

Alternative solutions could include task queues or some other cron-like approach using JSON/protobuf/etc. to serialize data but that's obviously pretty highly context dependent as to whether it's feasible.

**Comment by andrewplummer** [comment]
My understanding is that ndb deferred tasks are simply shortcuts for task queues, which are rather complicated to set up, so there is still a workaround. That said, if this is working as intended, then maybe it makes sense to add a note that the deferred library and potentially other libraries that make use of pickling are incompatible with GAE?
