### ISSUE TITLE
Changes to index.yaml occur in out/ not src/

### ISSUE THREAD

**Issue by paulbynd** [google/gae-secure-scaffold-python#32]
When running in development, the Python source code is run from `out`, which means that changes made by the development appserver to `index.yaml` are lost when rebuilding.

Are there best practices for detecting these changes and copying them back to `src`, or for running in development from `src` not `out`?

**Comment by pames** [comment]
Since we don't use the datastore in the base code, we've left this open for anyone to implement however they'd like.  You might be able to add some kind of Grunt task (grunt-contrib-watch) to watch a file like out/index.yaml and then copy it somewhere like a version controlled 'src/yaml/index.yaml' if there are changes.
